export default interface DormitoryAvatar {
  AvatarID: number
  RoleID: number
  Name: string
  QAvatarIcon: string
  NameText: Hash
  FaceAnimType: number
  MoveType: number
  KneelToAngry: number
  PairAvatarID: number
  JumpPar: number
  SitPar: number
  SitTime: number
  SitToSubAction: number
  SitToSleepPar: number
  SitToDrinkPar: number
  SitToEatPar: number
  SleepPar: number
  SleepTime: number
  GroundSitPar: number
  GroundSitTime: number
  GroundKneelPar: number
  GroundKneelTime: number
  LieDownPar: number
  LieDownTime: number
  LieDownToSubAction: number
  LieDownToSleepPar: number
  UseDeskPar: number
  UseDeskTime: number
  StandGamePar: number
  StandGameTime: number
  OpenFridgePar: number
  OpenFridgeTime: number
  OpenFridgeToDrinkPar: number
  OpenFridgeToEatPar: number
  WatchTVPar: number
  WatchTVTime: number
  StandBookPar: number
  StandBookTime: number
  StandArcadePar: number
  StandArcadeTime: number
  HandWritePar: number
  HandWriteTime: number
  PlayZhengPar: number
  PlayZhengTime: number
  PlayGoPar: number
  PlayGoTime: number
  StandEatPar: number
  StandEatIcePar: number
  BaseType: number
  SleepType: number
  DrinkType: number
  EatType: number
  TVShowType: number
  ComputerType: number
  ArcadeType: number
  LieDownType: number
  BookType: number
  HandWriteType: number
  UiOrder: number
}

interface Hash {
  Hash: number
}