export default interface Stigmata {
  ID: number
  Rarity: number
  MaxRarity: number
  SubRarity: number
  SubMaxRarity: number
  Cost: number
  PowerType: number
  MaxLv: number
  ExpType: number
  SellPriceBase: number
  SellPriceAdd: number
  GearExpProvideBase: number
  GearExpPorvideAdd: number
  BaseType: number
  LabelPath: string
  DisplayTitle: Hash
  DisplayDescription: Hash
  DisplayNumber: number
  IconPath: string
  ImagePath: string
  HPBase: number
  HPAdd: number
  SPBase: number
  SPAdd: number
  AttackBase: number
  AttackAdd: number
  DefenceBase: number
  DefenceAdd: number
  CriticalBase: number
  CriticalAdd: number
  DurabilityMax: number
  EvoMaterial: EvoMaterial[]
  EvoID: number
  Prop1ID: number
  Prop1Param1: number
  Prop1Param2: number
  Prop1Param3: number
  Prop1Param1Add: number
  Prop1Param2Add: number
  Prop1Param3Add: number
  Prop2ID: number
  Prop2Param1: number
  Prop2Param2: number
  Prop2Param3: number
  Prop2Param1Add: number
  Prop2Param2Add: number
  Prop2Param3Add: number
  Prop3ID: number
  Prop3Param1: number
  Prop3Param2: number
  Prop3Param3: number
  Prop3Param1Add: number
  Prop3Param2Add: number
  Prop3Param3Add: number
  Protect: boolean
  SetID: number
  SmallIcon: string
  TattooPath: string
  OffsetX: number
  OffsetY: number
  Scale: number
  AffixTreeId: number
  CanRefine: boolean
  RecycleID: number
  DisjoinScoinCost: number
  DisjoinAddMaterial: EvoMaterial[]
  LinkIDList: number[]
  Quality: number
  StigmataMainID: number
  ShortName: Hash
  SellPriceID: number
  Transcendent: boolean
  Target: number
  IsSecurityProtect: boolean
  GachaMainDropDisplayConfig: number[]
  GachaGiftDropDisplayConfig: any[]
  StigmataFilterList: number[]
  CollaborationSetID: number
}

interface EvoMaterial {
  ID: number
  Num: number
}

interface Hash {
  Hash: number
}